name: Lighthouse CI

on:
  push:
    branches:
      - tailWindSample

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Run Lighthouse CI
        run: npx lhci autorun --config .lighthouse.json
        
